-- 010_deprecated_keys.sql
-- Maps to LiteLLM_DeprecatedVerificationToken and LiteLLM_DeletedVerificationToken
-- Same schema as virtual_keys plus deprecated_at/deleted_at
-- PostgreSQL syntax

CREATE TABLE IF NOT EXISTS deprecated_keys (
    token TEXT NOT NULL,
    key_name TEXT,
    key_alias TEXT,
    soft_budget_cooldown TEXT NOT NULL DEFAULT 'false',
    spend DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    expires TIMESTAMPTZ(3),
    models JSONB NOT NULL,
    aliases JSONB NOT NULL,
    config JSONB NOT NULL,
    router_settings JSONB,
    user_id TEXT,
    team_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    permissions JSONB NOT NULL,
    max_parallel_requests INTEGER,
    metadata JSONB NOT NULL,
    blocked BOOLEAN,
    tpm_limit BIGINT,
    rpm_limit BIGINT,
    max_budget TEXT,
    budget_duration TEXT,
    budget_reset_at TIMESTAMPTZ(3),
    allowed_cache_controls JSONB NOT NULL,
    allowed_routes JSONB NOT NULL,
    policies JSONB NOT NULL,
    access_group_ids JSONB NOT NULL,
    model_spend JSONB NOT NULL,
    model_max_budget JSONB NOT NULL,
    budget_id TEXT,
    organization_id TEXT,
    object_permission_id TEXT,
    created_at TIMESTAMPTZ(3),
    created_by TEXT,
    updated_at TIMESTAMPTZ(3),
    updated_by TEXT,
    last_active TIMESTAMPTZ(3),
    rotation_count INTEGER,
    auto_rotate TEXT,
    rotation_interval TEXT,
    last_rotation_at TIMESTAMPTZ(3),
    key_rotation_at TIMESTAMPTZ(3),
    budget_limits JSONB,
    deprecated_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (token)
);

CREATE TABLE IF NOT EXISTS deleted_keys (
    token TEXT NOT NULL,
    key_name TEXT,
    key_alias TEXT,
    soft_budget_cooldown TEXT NOT NULL DEFAULT 'false',
    spend DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    expires TIMESTAMPTZ(3),
    models JSONB NOT NULL,
    aliases JSONB NOT NULL,
    config JSONB NOT NULL,
    router_settings JSONB,
    user_id TEXT,
    team_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    permissions JSONB NOT NULL,
    max_parallel_requests INTEGER,
    metadata JSONB NOT NULL,
    blocked BOOLEAN,
    tpm_limit BIGINT,
    rpm_limit BIGINT,
    max_budget TEXT,
    budget_duration TEXT,
    budget_reset_at TIMESTAMPTZ(3),
    allowed_cache_controls JSONB NOT NULL,
    allowed_routes JSONB NOT NULL,
    policies JSONB NOT NULL,
    access_group_ids JSONB NOT NULL,
    model_spend JSONB NOT NULL,
    model_max_budget JSONB NOT NULL,
    budget_id TEXT,
    organization_id TEXT,
    object_permission_id TEXT,
    created_at TIMESTAMPTZ(3),
    created_by TEXT,
    updated_at TIMESTAMPTZ(3),
    updated_by TEXT,
    last_active TIMESTAMPTZ(3),
    rotation_count INTEGER,
    auto_rotate TEXT,
    rotation_interval TEXT,
    last_rotation_at TIMESTAMPTZ(3),
    key_rotation_at TIMESTAMPTZ(3),
    budget_limits JSONB,
    deleted_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    PRIMARY KEY (token)
);
