-- 001_virtual_keys.sql
-- Maps to LiteLLM_VerificationToken table (column-compatible)
-- SQLite syntax

CREATE TABLE IF NOT EXISTS virtual_keys (
    token TEXT PRIMARY KEY,
    key_name TEXT,
    key_alias TEXT,
    soft_budget_cooldown TEXT NOT NULL DEFAULT 'false',
    spend REAL NOT NULL DEFAULT 0.0,
    expires DATETIME,
    models BLOB NOT NULL,
    aliases BLOB NOT NULL,
    config BLOB NOT NULL,
    router_settings BLOB,
    user_id TEXT,
    team_id TEXT,
    agent_id TEXT,
    project_id TEXT,
    permissions BLOB NOT NULL,
    max_parallel_requests INTEGER,
    metadata BLOB NOT NULL,
    blocked INTEGER,
    tpm_limit INTEGER,
    rpm_limit INTEGER,
    max_budget TEXT,
    budget_duration TEXT,
    budget_reset_at DATETIME,
    allowed_cache_controls BLOB NOT NULL,
    allowed_routes BLOB NOT NULL,
    policies BLOB NOT NULL,
    access_group_ids BLOB NOT NULL,
    model_spend BLOB NOT NULL,
    model_max_budget BLOB NOT NULL,
    budget_id TEXT,
    organization_id TEXT,
    object_permission_id TEXT,
    created_at DATETIME,
    created_by TEXT,
    updated_at DATETIME,
    updated_by TEXT,
    last_active DATETIME,
    rotation_count INTEGER,
    auto_rotate TEXT,
    rotation_interval TEXT,
    last_rotation_at DATETIME,
    key_rotation_at DATETIME,
    budget_limits BLOB
);
