//! Integration test: verify decrypt_json_fields correctly decrypts
//! litellm_params and credential_values without requiring a live upstream
//! database connection.
//!
//! Fixtures are generated by `export_fixtures` (run manually when upstream
//! DB is accessible) and stored in `tests/fixtures/encrypted_params_fixtures.json`.
//!
//! The fixture data is encrypted with the publicly-known test key so no
//! real secrets are exposed.

use aigw_core::crypto::{decrypt_json_fields, decrypt_litellm_value};
use serde::Deserialize;
use serde_json::Value;

/// The fixed test key used for all fixtures.  This is intentionally public.
const TEST_MASTER_KEY: &str = "sk-test-fixture-key-0000000000000000";

#[derive(Debug, Deserialize)]
struct FixtureFile {
    models: Vec<ModelFixture>,
}

#[derive(Debug, Deserialize)]
struct ModelFixture {
    model_name: String,
    encrypted_litellm_params: String,
    encrypted_credential_values: Option<String>,
    expected_api_base_suffix: Option<String>,
    expected_model: Option<String>,
}

/// Heuristic: does `s` still look like a litellm-encrypted value?
fn looks_encrypted(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    if s.starts_with("v2:gcm:") {
        return true;
    }
    if s.starts_with("sk-")
        || s.starts_with("http://")
        || s.starts_with("https://")
        || s.starts_with("Bearer ")
        || s.starts_with('{')
    {
        return false;
    }
    s.len() >= 60
        && s.bytes().all(|b| {
            b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'=' || b == b'-' || b == b'_'
        })
        && !s.contains(' ')
}

fn collect_string_leaves(value: &Value, prefix: &str, results: &mut Vec<(String, String)>) {
    match value {
        Value::Object(map) => {
            for (k, v) in map {
                collect_string_leaves(v, &format!("{}.{}", prefix, k), results);
            }
        }
        Value::Array(arr) => {
            for (i, v) in arr.iter().enumerate() {
                collect_string_leaves(v, &format!("{}[{}]", prefix, i), results);
            }
        }
        Value::String(s) => {
            results.push((prefix.to_string(), s.clone()));
        }
        _ => {}
    }
}

fn load_fixtures() -> FixtureFile {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/encrypted_params_fixtures.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read fixture file {}: {}", path.display(), e));
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("Failed to parse fixture file {}: {}", path.display(), e))
}

#[test]
fn verify_nested_decrypt_for_all_fixtures() {
    let fixtures = load_fixtures();

    assert!(
        !fixtures.models.is_empty(),
        "fixture file must contain at least one model"
    );

    let mut any_failure = false;

    for m in &fixtures.models {
        println!("\n--- 模型: {} ---", m.model_name);

        // 1. Decrypt litellm_params with test key
        let params_str = decrypt_litellm_value(&m.encrypted_litellm_params, TEST_MASTER_KEY)
            .unwrap_or_else(|e| panic!("Failed to decrypt litellm_params for {}: {}", m.model_name, e));
        let params_json: Value =
            serde_json::from_str(&params_str).expect("litellm_params must be valid JSON");

        // 2. Collect encrypted fields BEFORE nested decryption
        let mut before_leaves = Vec::new();
        collect_string_leaves(&params_json, "litellm_params", &mut before_leaves);
        let before_encrypted: Vec<_> = before_leaves
            .iter()
            .filter(|(_, v)| looks_encrypted(v))
            .map(|(p, _)| p.clone())
            .collect();

        // 3. Apply nested decryption (decrypt_json_fields)
        let decrypted = decrypt_json_fields(&params_json, TEST_MASTER_KEY);

        // 4. Collect string leaves AFTER nested decryption
        let mut after_leaves = Vec::new();
        collect_string_leaves(&decrypted, "litellm_params", &mut after_leaves);

        // 5. No field should still look encrypted
        let still_encrypted: Vec<_> = after_leaves
            .iter()
            .filter(|(_, v)| looks_encrypted(v))
            .collect();
        if still_encrypted.is_empty() {
            println!(
                "  [OK] litellm_params 全部解密成功 ({}/{} encrypted → 0 残留)",
                before_encrypted.len(),
                after_leaves.len(),
            );
        } else {
            for (path, value) in &still_encrypted {
                println!(
                    "  [FAIL] {} = {} (仍然加密!)",
                    path,
                    &value[..value.len().min(60)]
                );
                any_failure = true;
            }
        }

        // 6. Sanity-check expected plaintext fields
        if let Some(ref suffix) = m.expected_api_base_suffix {
            let api_base = decrypted
                .get("api_base")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let matches = api_base.contains(suffix.as_str());
            println!(
                "  api_base check: suffix='{}' found={}",
                suffix, matches
            );
            if !matches {
                println!("  [FAIL] api_base '{}' does not contain '{}'", api_base, suffix);
                any_failure = true;
            }
        }
        if let Some(ref expected) = m.expected_model {
            let model = decrypted
                .get("model")
                .and_then(|v| v.as_str())
                .unwrap_or("");
            let matches = model == expected.as_str();
            println!("  model check: expected='{}' actual='{}' ok={}", expected, model, matches);
            if !matches {
                println!("  [FAIL] model mismatch: expected '{}' got '{}'", expected, model);
                any_failure = true;
            }
        }

        // 7. Verify credential_values if present
        if let Some(ref enc_cred) = m.encrypted_credential_values {
            println!("  → 验证 credential_values...");
            let cred_str = decrypt_litellm_value(enc_cred, TEST_MASTER_KEY)
                .unwrap_or_else(|e| panic!("Failed to decrypt credential_values: {}", e));
            let cred_json: Value =
                serde_json::from_str(&cred_str).expect("credential_values must be valid JSON");
            let cred_decrypted = decrypt_json_fields(&cred_json, TEST_MASTER_KEY);

            let mut cred_after = Vec::new();
            collect_string_leaves(&cred_decrypted, "credential_values", &mut cred_after);

            let cred_still: Vec<_> = cred_after
                .iter()
                .filter(|(_, v)| looks_encrypted(v))
                .collect();
            if cred_still.is_empty() {
                println!("  [OK] credential_values 全部解密成功 ({} 字段)", cred_after.len());
            } else {
                for (path, value) in &cred_still {
                    println!(
                        "  [FAIL] {} = {} (仍然加密!)",
                        path,
                        &value[..value.len().min(60)]
                    );
                    any_failure = true;
                }
            }
        }
    }

    if any_failure {
        panic!("有些字段未能成功解密, 详情见上面 [FAIL] 输出");
    }
    println!("\n=== 全部模型验证通过 ===");
}
