-- 001_virtual_keys.sql
-- Maps to LiteLLM_VerificationToken table (column-compatible)
-- MySQL syntax

CREATE TABLE IF NOT EXISTS virtual_keys (
    token VARCHAR(255) NOT NULL,
    key_name VARCHAR(255),
    key_alias VARCHAR(255),
    soft_budget_cooldown TEXT NOT NULL,
    spend DOUBLE NOT NULL DEFAULT 0.0,
    expires DATETIME(3),
    models JSON NOT NULL,
    aliases JSON NOT NULL,
    config JSON NOT NULL,
    router_settings JSON,
    user_id VARCHAR(255),
    team_id VARCHAR(255),
    agent_id VARCHAR(255),
    project_id VARCHAR(255),
    permissions JSON NOT NULL,
    max_parallel_requests TEXT,
    metadata JSON NOT NULL,
    blocked TINYINT(1),
    tpm_limit TEXT,
    rpm_limit TEXT,
    max_budget TEXT,
    budget_duration VARCHAR(255),
    budget_reset_at DATETIME(3),
    allowed_cache_controls JSON NOT NULL,
    allowed_routes JSON NOT NULL,
    policies JSON NOT NULL,
    access_group_ids JSON NOT NULL,
    model_spend JSON NOT NULL,
    model_max_budget JSON NOT NULL,
    budget_id VARCHAR(255),
    organization_id VARCHAR(255),
    object_permission_id VARCHAR(255),
    created_at DATETIME(3),
    created_by VARCHAR(255),
    updated_at DATETIME(3),
    updated_by VARCHAR(255),
    last_active DATETIME(3),
    rotation_count INTEGER,
    auto_rotate TEXT,
    rotation_interval VARCHAR(255),
    last_rotation_at DATETIME(3),
    key_rotation_at DATETIME(3),
    budget_limits JSON,
    PRIMARY KEY (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
